<?php

namespace Samye\EvtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvtCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtCategoryRepository extends EntityRepository
{
}
