<?php

namespace Samye\EvtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvtStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtStatusRepository extends EntityRepository
{
}
