parameters:
#    samye_user.example.class: Samye\UserBundle\Example

services:
#    samye_user.example:
#        class: %samye_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    
    samye_user.registration.form.type:
        class: Samye\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: samye_user_registration }