parameters:
#    samye_user.example.class: Samye\UserBundle\Example

services:
#    samye_user.example:
#        class: %samye_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
