<?php

namespace Samye\EvtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Categorie_EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_EvenementRepository extends EntityRepository
{
}
