samye_index:
    pattern: /
    defaults: {_controller: SamyeEvtBundle:Evt:index}

samye_evt:
    pattern: /events
    defaults: {_controller: SamyeEvtBundle:Evt:events}

samye_voir:
    pattern: /event/{id}
    defaults: {_controller: SamyeEvtBundle:Evt:voir}

samye_add_event:
    pattern: /addEvent
    defaults: {_controller: SamyeEvtBundle:Evt:addEvent}

samye_modify:
    pattern: /modify/{id}
    defaults: {_controller: SamyeEvtBundle:Evt:modify}

samye_delete:
    pattern: /delete/{id}
    defaults: {_controller: SamyeEvtBundle:Evt:delete}
    
samye_voir_evt_cal:
    pattern: /vcal
    defaults: {_controller: SamyeEvtBundle:Evt:voirEvtCal}

samye_evt_cal:
    pattern: /vcal/
    defaults: {_controller: SamyeEvtBundle:Evt:evtCal}
    requirements:
        _method: POST