samye_index:
    pattern: /
    defaults: {_controller: SamyeEvtBundle:Evt:index}

samye_vueGenerale:
    pattern: /vueGenerale
    defaults: {_controller: SamyeEvtBundle:Evt:vueGenerale}

samye_evt:
    pattern: /events
    defaults: {_controller: SamyeEvtBundle:Evt:allEvents}

samye_pers_evt:
    pattern: /myEvents
    defaults: {_controller: SamyeEvtBundle:Evt:personalEvents}

samye_show_event:
    pattern: /showEvent/{id}
    defaults: {_controller: SamyeEvtBundle:Evt:showEvent}

samye_add_event:
    pattern: /addEvent
    defaults: {_controller: SamyeEvtBundle:Evt:addEvent}

samye_modify_event:
    pattern: /modifyEvent/{id}
    defaults: {_controller: SamyeEvtBundle:Evt:modifyEvent}

samye_delete_event:
    pattern: /deleteEvent/{id}
    defaults: {_controller: SamyeEvtBundle:Evt:deleteEvent}

samye_categories:
    pattern: /categories
    defaults: {_controller: SamyeEvtBundle:Categories:categories}

samye_show_category:
    pattern: /category/{id}
    defaults: {_controller: SamyeEvtBundle:Categories:showCategory}	

samye_add_category:
    pattern: /addCategory
    defaults: {_controller: SamyeEvtBundle:Categories:addCategory}

samye_modify_category:
    pattern: /modifyCategory/{id}
    defaults: {_controller: SamyeEvtBundle:Categories:modifyCategory}

samye_delete_category:
    pattern: /deleteCategory/{id}
    defaults: {_controller: SamyeEvtBundle:Categories:deleteCategory}

samye_voir_evt_cal:
    pattern: /vcal
    defaults: {_controller: SamyeEvtBundle:Evt:voirEvtCal}

samye_resume_evt_cal:
    pattern: /vcal/
    defaults: {_controller: SamyeEvtBundle:Evt:evtCal}
    requirements:
        _method: POST